/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import { useRouter } from "next/router";

const forgot4 = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div>
          <a href="/forgot3" className="BackButton">
            Back
          </a>
          <div className="ForgotText">Password reset</div>
          <div className="ForgotText1">
            Your password has been successfully reset. <br />
            Click below to log in magically
          </div>
          <button
            className="InstructionButton3"
            onClick={() => {
              router.push("/loginpage");
            }}
          >
            <p className="inner-btn">Continue</p>
          </button>
        </div>
      </main>
    </div>
  );
};

export default forgot4;
